### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by AndroFlo** [adroitandroid/Near#5]
Hello, 

I have this error sometimes.

Fatal Exception: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at com.adroitandroid.near.connect.TcpServerService.onNewReceive(TcpServerService.java:131)
       at com.adroitandroid.near.connect.TcpServerService.access$300(TcpServerService.java:25)
       at com.adroitandroid.near.connect.TcpServerService$1$1.run(TcpServerService.java:81)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by adroitandroid** [comment]
Can you get a thread dump?

**Comment by AndroFlo** [comment]
Only appear one time
